---
title: "Analysis4ABCDE_PNICO_importance_feature.Rmd"
author: "Xiaochun Han"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
rm(list = ls())
source("../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix","kableExtra","lime","ggbeeswarm"))
```

## Import data
```{r impart_data,eval=FALSE}
setwd('../Data/Develop')
wd<-getwd()
dataset_BNS <- read.csv('BINS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_WNS <- read.csv('INS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

WNS_mean = extract_win_or_pay_mean(dataset_WNS,dataset_y_attack,"WNS_","win",FALSE)
BNS_mean = extract_win_or_pay_mean(dataset_BNS,dataset_y_attack,"BNS_","win",FALSE)
data_WNS_BNS_invest = cbind(WNS_mean[,c(1,3:ncol(WNS_mean))],BNS_mean[,3:ncol(BNS_mean)])
```

## Feature importance analysis
```{r svm_feat_impor,eval=FALSE}
featSet = colnames(data_WNS_BNS_invest[,2:ncol(data_WNS_BNS_invest)])
fi_fs_invest = list()
for (f in 1:length(featSet)){
  fi_invest = svm_feat_impor(data_WNS_BNS_invest,featSet[f],5,100,5000)
  fi_fs_invest[[f]] = fi_invest
  names(fi_fs_invest)[f] = featSet[f]
}
saveRDS(fi_fs_invest, file = "fi_all_invest_WNS_BNS_5000.RData")
```

### Feature importance read
```{r read_feat_impor}
fi_fs_invest = readRDS("fi_all_invest_WNS_BNS_5000.RData")
acc_ins_bins = 0.9212
dec_acc = vector(length = 112)
for (v in 1:length(fi_fs_invest)){
  dec_acc[v] = (acc_ins_bins - mean(fi_fs_invest[[v]][[2]]$acc_perm))*100
}

fi_all <- data.frame(
  name = names(fi_fs_invest),
  fi_value_percent = dec_acc)

fi_sorted <- fi_all %>%
  arrange(
    desc(grepl("Attack", name)),  
    desc(grepl("_L_", name)),       
    desc(grepl("WNS", name)),
    desc(grepl("rDLPFC", name))  
  )
```

### Feature importance print
```{r fi_print, results='asis'}
n_groups <- ceiling(nrow(fi_sorted) / 7)
for (i in 1:n_groups) {
  start_row <- (i-1)*7 + 1
  end_row <- min(i*7, nrow(fi_sorted))
  group_data <- fi_sorted[start_row:end_row, ]
  simple_table <- knitr::kable(group_data, caption = paste("Feature Set", i)) %>%
  kableExtra::kable_styling(
  bootstrap_options = c("striped", "hover"),
  full_width = FALSE,
  position = "left"
  )
  print(simple_table)
  cat("\n\n")
}
```

## Attack vs. Defender
### ttest
```{r ttest-fi-ad}
fi_A = fi_all$fi_value_percent[grepl('_Attack_', fi_all$name)]
fi_D = fi_all$fi_value_percent[grepl('_Defend_', fi_all$name)]
df = data.frame(fi_A, fi_D)
df <- df %>% gather(key = "feature", value = "value")
df %>% group_by(feature) %>% summarize(mean = mean(value), sd = sd(value))
t.test(value~feature, data = df, var.equal = TRUE)
cohens_d(value~feature, data = df, var.equal = TRUE)
```

### figure
```{r figure-fi-ad}
summary_data <- df %>% group_by(feature) %>% summarize(Mean = mean(value), SE = sd(value)/sqrt(n()))
p<-ggplot(summary_data, aes(x = feature, y = Mean, fill = feature)) +
  geom_hline(aes(yintercept = 0), color = "black", linewidth = 0.8, linetype = 1) +
  geom_col(width = 0.6, color = "black") +
  scale_fill_manual(values = c("#0D0D0D","#BFBFBF"))+
  geom_jitter(
    data = df,
    aes(y = value, x = feature),
    width = 0, size = 2, alpha = 0.6, color = "grey"
  ) +
  geom_errorbar(
    aes(ymin = Mean - SE, ymax = Mean + SE),
    width = 0.2, color = "black", size = 0.5
  ) +
  scale_y_continuous(
    limits = c(-0.5, 1),              
    breaks = c(-0.5, 0, 0.5, 1)  
  )  +
  theme_classic()+
  theme(legend.position = "none")
print(p)
```

## Leader vs. Follower
### ttest
```{r ttest-fi-lf}
fi_L = fi_all$fi_value_percent[grepl('_L_', fi_all$name)]
fi_F = fi_all$fi_value_percent[grepl('_F_', fi_all$name)]
df = data.frame(fi_L, fi_F)
df <- df %>% gather(key = "feature", value = "value")
df %>% group_by(feature) %>% summarize(mean = mean(value), sd = sd(value))
t.test(value~feature, data = df, var.equal = TRUE)
cohens_d(value~feature, data = df, var.equal = TRUE)
```

### figure
```{r figure-fi-lf}
summary_data <- df %>% group_by(feature) %>% summarize(Mean = mean(value), SE = sd(value)/sqrt(n()))
summary_data$feature = factor(summary_data$feature, levels = c("fi_L","fi_F"))
p<-ggplot(summary_data, aes(x = feature, y = Mean, fill = feature)) +
  geom_hline(aes(yintercept = 0), color = "black", linewidth = 0.8, linetype = 1) +
  geom_col(width = 0.6, color = "black") +
  scale_fill_manual(values = c("#DA6F6F","#F29697"))+
  geom_jitter(
    data = df,
    aes(y = value, x = feature),
    width = 0, size = 2, alpha = 0.6, color = "grey"
  ) +
  geom_errorbar(
    aes(ymin = Mean - SE, ymax = Mean + SE),
    width = 0.2, color = "black", size = 0.5
  ) +
  scale_y_continuous(
    limits = c(-0.5, 1),                
    breaks = c(-0.5, 0, 0.5, 1)  
  ) +
  theme_classic()+
  theme(legend.position = "none")
print(p)
```

## Top features
### Feature selection
```{r fi-select}
threshold_value <- mean(fi_all$fi_value_percent) + sd(fi_all$fi_value_percent)

filtered_fi <- fi_all %>%
  filter(fi_value_percent > threshold_value) %>%  
  arrange(desc(fi_value_percent))
```

### figure
```{r figure_top14}
color_vector <- sapply(filtered_fi$name, function(x) {
  if (grepl("WNS", x)) return("#B195C6")
  if (grepl("BNS", x)) return("#E5DCF2")
})

filtered_fi$name <- factor(filtered_fi$name, levels = filtered_fi$name)

p <- ggplot(filtered_fi) +
  geom_bar(aes(x = name, y = fi_value_percent, fill = color_vector), stat = "identity") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 0), legend.position = "none") +
  labs(x = "Feature space", y = "Feature importance") +
  scale_fill_identity() +
  theme(text = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90),
        panel.background = element_rect(fill = "transparent", color = NA),
        plot.background = element_rect(fill = "transparent", color = NA))

print(p)
```

## Directional influence
### LIME analysis
```{r lime,eval=FALSE}
data_WNS_BNS_invest_selected = data_WNS_BNS_invest %>%
  select(c(any_of(as.character(filtered_fi$name)), "good_1")) %>%
  relocate("good_1", .before = 1)
weight = svm_lime(data_WNS_BNS_invest_selected,data_WNS_BNS_invest_selected,2,"yes",14,"none")
```

### figure
```{r figure}
weight = readRDS("svm_win_WNS_BNS_lime_separate_2bin_yes_14_none.RData")

for (i in 1:3) {
    current_mean <- mean(weight$feature_weight, na.rm = TRUE)
    current_sd <- sd(weight$feature_weight, na.rm = TRUE)
    upper_lim <- current_mean + 3 * current_sd
    lower_lim <- current_mean - 3 * current_sd
    
    na_before <- sum(is.na(weight$feature_weight))
    weight$feature_weight[weight$feature_weight > upper_lim | weight$feature_weight < lower_lim] <- NA
    new_na <- sum(is.na(weight$feature_weight)) - na_before
    
    cat("第", i, "轮: 均值=", round(current_mean, 4), "SD=", round(current_sd, 4),
        "新增异常值=", new_na, "\n")
  }
  
  cat("最终NA值数量:", sum(is.na(weight$feature_weight)), "\n")

my_custom_order <- c(
  'BNS_Attack_L_rDLPFC_CH12',
  'WNS_Attack_F_rDLPFC_CH12',
  'WNS_Attack_F_rDLPFC_CH14',
  'WNS_Attack_F_rDLPFC_CH11',
  'WNS_Attack_L_rDLPFC_CH06',
  'WNS_Attack_F_rDLPFC_CH02',
  'BNS_Attack_L_rDLPFC_CH14',
  'WNS_Attack_L_rDLPFC_CH14',
  'BNS_Attack_L_rDLPFC_CH11',
  'WNS_Defend_L_rDLPFC_CH14',
  'BNS_Defend_L_rTPJ_CH13',
  'BNS_Defend_L_rTPJ_CH09',
  'BNS_Attack_F_rTPJ_CH13',
  'WNS_Attack_L_rTPJ_CH09')

weight$feature <- factor(weight$feature, levels = my_custom_order)

weight$type[weight$feature_value > 0] = 'pos'
weight$type[weight$feature_value < 0] = 'neg'

ggplot(weight, aes(x = feature, y = feature_weight, color = feature_value))+
  geom_hline(yintercept = 0) +
  geom_quasirandom(bandwidth = 0.1,size = 3) + 
  scale_fill_manual(values = c("white", "white"))+
  scale_color_gradientn(colours = c('#1F4E79', '#2E75B6','white','#D96F6F','#931624'),limits = c(-5, 5),breaks = c(-5, 0, 5)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```