---
title: "Analysis3AB_Accuracy_decomposition"
author: "Xiaochun Han"
date: "2025-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix","pROC"))
```

## Import data
```{r impart data}
dataset_pseudo <- read.csv('Pseudo_pair_control.csv',header=TRUE,sep=",")
dataset_circular <- read.csv('Circular_time_control.csv',header=TRUE,sep=",")
dataset_machine <- read.csv('Same_machine_control.csv',header=TRUE,sep=",")
```

### Pseudo_pair_control
```{r permute_pseudo}
acc_low_25 = sort(dataset_pseudo$Var1)[25]
acc_top_25 = sort(dataset_pseudo$Var1)[975]
dataset_pseudo$ci95 = rep(0,1000)
dataset_pseudo$ci95[(dataset_pseudo$Var1<acc_low_25|dataset_pseudo$Var1>acc_top_25)] = 1
acc_all = 0.9212
p_perm = mean(acc_all<dataset_pseudo$Var1)

p<-ggplot(dataset_pseudo, aes(x = Var1, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#B095C6"))+
    geom_vline(aes(xintercept = acc_all), color = "#B095C6", linewidth = 2) + theme_classic()+xlim(0.5,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 25),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```

### Circular_time_control
```{r permute_circular}
acc_low_25 = sort(dataset_circular$Var1)[25]
acc_top_25 = sort(dataset_circular$Var1)[975]
dataset_circular$ci95 = rep(0,1000)
dataset_circular$ci95[(dataset_circular$Var1<acc_low_25|dataset_circular$Var1>acc_top_25)] = 1
acc_all = 0.9212
p_perm = mean(acc_all<dataset_circular$Var1)

p<-ggplot(dataset_circular, aes(x = Var1, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#B095C6"))+
    geom_vline(aes(xintercept = acc_all), color = "#B095C6", linewidth = 2) + theme_classic()+xlim(0.7,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 25),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```

### Same_machine_control
```{r permute_machine}
acc_low_25 = sort(dataset_machine$Var1)[25]
acc_top_25 = sort(dataset_machine$Var1)[975]
dataset_machine$ci95 = rep(0,1000)
dataset_machine$ci95[(dataset_machine$Var1<acc_low_25|dataset_machine$Var1>acc_top_25)] = 1
acc_all = 0.9212
p_perm = mean(acc_all<dataset_machine$Var1)

p<-ggplot(dataset_machine, aes(x = Var1, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#B095C6"))+
    geom_vline(aes(xintercept = acc_all), color = "#B095C6", linewidth = 2) + theme_classic()+xlim(0.5,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 25),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```
```{r permute_machine}
# 1. 准备数据
categories <- c('chance level', 'imbalanced trial', 'real-time interaction (other)', 'precise temporal alignment', 'states', 'others')
percentages <- c(50, 20, 11, 6, 5, 8) # 17%的interaction拆分为11%+6%
colors <- c('#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', 'purple','#FFEAA7') # 为每个类别设置颜色

# 2. 绘制饼图
# 设置画布，确保标题完整显示
par(mar = c(2, 2, 3, 2))
# 绘制饼图，并显示百分比标签
pie(percentages,
    labels = paste0(percentages, "%"), # 在扇区上直接显示百分比
    col = colors,
    main = "Pie",
    clockwise = TRUE, # 从12点方向开始顺时针绘制
    init.angle = 90) # 起始角度为90度（12点方向）

# 3. 添加图例
legend("topright", 
       legend = categories, 
       fill = colors, 
       title = "condition",
       cex = 0.8) # 调整图例文字大小
```
