---
title: "S01_SVM_outcome_prediction"
author: "Xiaochun Han"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix"))
```

## Import data
```{r import data}
setwd('../../Data/Develop')
wd<-getwd()
dataset_BOLD <- read.csv('BOLD_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_FC <- read.csv('FC_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_BINS <- read.csv('BINS_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_outcome.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

BOLD_mean = extract_win_or_pay_mean(dataset_BOLD,dataset_y_attack,"BOLD_","win",FALSE)
FC_mean = extract_win_or_pay_mean(dataset_FC,dataset_y_attack,"FC_","win",FALSE)
INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE)
data_all_outcome = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_INS_BINS_outcome = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)])
data_BOLD_FC_outcome = cbind(BOLD_mean[,c(1,3:ncol(BOLD_mean))],FC_mean[,3:ncol(FC_mean)])

data_WNS_outcome = INS_mean[,c(1,3:ncol(INS_mean))]
data_BNS_outcome = BINS_mean[,c(1,3:ncol(BINS_mean))]
data_BOLD_outcome = BOLD_mean[,c(1,3:ncol(BOLD_mean))]
data_FC_outcome = FC_mean[,c(1,3:ncol(FC_mean))]

data_minus_WNS_outcome = cbind(BINS_mean[,c(1,3:ncol(BINS_mean))],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_BNS_outcome = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_BOLD_outcome = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_FC_outcome = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],BOLD_mean[,3:ncol(BOLD_mean)])
```

## Predicting win vs. lose
### All features
```{r svm_invest_all}
acc_all = svm_cv_accuracy(data_all_outcome,5,100,"radial")
print(acc_all)
```

```{r permute_all-5}
acc_all_perm = readRDS("SVM_win_data_all_outcome_phase_perm_5000.RData")
acc_all_low_25 = sort(acc_all_perm$acc_perm)[125]
acc_all_top_25 = sort(acc_all_perm$acc_perm)[4875]
acc_all_perm$ci95 = rep(0,5000)
acc_all_perm$ci95[(acc_all_perm$acc_perm<acc_all_low_25|acc_all_perm$acc_perm>acc_all_top_25)] = 1
p_all_perm = mean(acc_all<acc_all_perm$acc_perm)
print(p_all_perm)

p<-ggplot(acc_all_perm, aes(x = acc_perm, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#000000"))+
    geom_vline(aes(xintercept = acc_all), color = "#000000", linewidth = 1.5) + theme_classic()+xlim(0,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 15),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = svm_cv_accuracy(data_BOLD_FC_outcome,5,100,"radial")
print(acc_bold_fc)
```

```{r svm_invest_BOLD&FC-5}
acc_bold_fc_perm = readRDS("SVM_win_data_BOLD_FC_outcome_phase_perm_5000.RData")
acc_low_25 = sort(acc_bold_fc_perm$acc_perm)[125]
acc_top_25 = sort(acc_bold_fc_perm$acc_perm)[4875]
acc_bold_fc_perm$ci95 = rep(0,5000)
acc_bold_fc_perm$ci95[(acc_bold_fc_perm$acc_perm<acc_low_25|acc_bold_fc_perm$acc_perm>acc_top_25)] = 1
p_bold_fc_perm = mean(acc_bold_fc<acc_bold_fc_perm$acc_perm)
print(p_bold_fc_perm)

p<-ggplot(acc_bold_fc_perm, aes(x = acc_perm, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#969796"))+
    geom_vline(aes(xintercept = acc_bold_fc), color = "#969796", linewidth = 2) + theme_classic()+xlim(0,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 15),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```

### INS and BINS
```{r svm_invest_INS&BINS}
acc_wns_bns = svm_cv_accuracy(data_INS_BINS_outcome,5,100,"radial")
print(acc_wns_bns)
```

```{r permute_INS&BINS-5}
acc_wns_bns_perm = readRDS("SVM_win_data_WNC_BNC_outcome_phase_perm_5000.RData")
acc_low_25 = sort(acc_wns_bns_perm$acc_perm)[125]
acc_top_25 = sort(acc_wns_bns_perm$acc_perm)[4875]
acc_wns_bns_perm$ci95 = rep(0,5000)
acc_wns_bns_perm$ci95[(acc_wns_bns_perm$acc_perm<acc_low_25|acc_wns_bns_perm$acc_perm>acc_top_25)] = 1
p_wns_bns_perm = mean(acc_wns_bns<acc_wns_bns_perm$acc_perm)
print(p_wns_bns_perm)

p<-ggplot(acc_wns_bns_perm, aes(x = acc_perm, fill = as.factor(ci95))) +
    geom_histogram(colour = "#4C4C4C", bins = 61) + 
    scale_fill_manual(values = c("white","#B095C6"))+
    geom_vline(aes(xintercept = acc_wns_bns), color = "#B095C6", linewidth = 2) + theme_classic()+xlim(0,1) + 
    labs(x = "Win-Lose Prediction Accuracy") + theme(text = element_text(size = 15),legend.position="none",axis.ticks.length=unit(-0.1, "cm"))
print(p)
```

### minus WNS
```{r svm_invest_minus_WNS}
acc_minus_wns = svm_cv_accuracy(data_minus_WNS_outcome,5,100,"radial")
print(acc_minus_wns)
```

### minus BNS
```{r svm_invest_minus_BNS}
acc_minus_bns = svm_cv_accuracy(data_minus_BNS_outcome,5,100,"radial")
print(acc_minus_bns)
```

### minus BOLD
```{r svm_invest_minus_BOLD}
acc_minus_bold = svm_cv_accuracy(data_minus_BOLD_outcome,5,100,"radial")
print(acc_minus_bold)
```

### minus FC
```{r svm_invest_minus_FC}
acc_minus_fc = svm_cv_accuracy(data_minus_FC_outcome,5,100,"radial")
print(acc_minus_fc)
```

### INS
```{r svm_invest_INS}
acc_wns = svm_cv_accuracy(data_WNS_outcome,5,100,"radial")
print(acc_wns)
```

### BNS
```{r svm_invest_BNS}
acc_bns = svm_cv_accuracy(data_BNS_outcome,5,100,"radial")
print(acc_bns)
```

### BOLD
```{r svm_invest_BOLD}
acc_bold = svm_cv_accuracy(data_BOLD_outcome,5,100,"radial")
print(acc_bold)
```

### FC
```{r svm_invest_FC}
acc_fc = svm_cv_accuracy(data_FC_outcome,5,100,"radial")
print(acc_fc)
```
