---
title: "Analysis4ABCD_Feature_importance_analysis.Rmd"
author: "Xiaochun Han"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
rm(list = ls())
source("../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix","kableExtra"))
```

## Import data
```{r impart_data,eval=FALSE}
setwd('../Data/Develop')
wd<-getwd()
dataset_BNS <- read.csv('BINS_single_trial.csv',header=TRUE,sep=",")
dataset_WNS <- read.csv('INS_single_trial.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

WNS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE)
BNS_mean = extract_win_or_pay_mean(dataset_BNS,dataset_y_attack,"BNS_","win",FALSE)
data_WNS_BNS_invest = cbind(WNS_mean[,c(1,4:ncol(WNS_mean))],BNS_mean[,4:ncol(BNS_mean)])
```

## Feature importance analysis
```{r svm_feat_impor,eval=FALSE}
featSet = colnames(data_WNS_BNS_invest[,2:ncol(data_WNS_BNS_invest)])
fi_fs_invest = list()
for (f in 1:length(featSet)){
  fi_invest = svm_feat_impor(data_WNS_BNS_invest,featSet[f],5,100,5000)
  fi_fs_invest[[f]] = fi_invest
  names(fi_fs_invest)[f] = featSet[f]
}
saveRDS(fi_fs_invest, file = "fi_all_invest_WNS_BNS_5000.RData")
```

### Feature importance read
```{r read_feat_impor}
fi_fs_invest = readRDS("fi_all_invest_WNS_BNS_5000.RData")

dec_acc = vector(length = 112)
for (v in 1:length(fi_fs_invest)){
  dec_acc[v] = fi_fs_invest[[v]][[3]][[1]]*100
}

fi_all <- data.frame(
  name = names(fi_fs_invest),
  fi_value_percent = dec_acc)

fi_sorted <- fi_all %>%
  arrange(
    desc(grepl("Attack", name)),  
    desc(grepl("_L_", name)),       
    desc(grepl("WNS", name)),
    desc(grepl("rDLPFC", name))  
  )
```

### Feature importance print
```{r fi_print, results='asis'}
n_groups <- ceiling(nrow(fi_sorted) / 7)
for (i in 1:n_groups) {
  start_row <- (i-1)*7 + 1
  end_row <- min(i*7, nrow(fi_sorted))
  group_data <- fi_sorted[start_row:end_row, ]
  simple_table <- knitr::kable(group_data, caption = paste("Feature Set", i)) %>%
  kableExtra::kable_styling(
  bootstrap_options = c("striped", "hover"),
  full_width = FALSE,
  position = "left"
  )
  print(simple_table)
  cat("\n\n")
}
```
