---
title: "S02_Hyperparameter_tuning"
author: "Xiaochun Han"
date: "2025-12-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix", "glmnet", "LiblineaR"))
```

## Import data
```{r impart data}
setwd('../../Data/Develop')
wd<-getwd()
dataset_BOLD <- read.csv('BOLD_single_trial_invest.csv',header=TRUE,sep=",")
dataset_FC <- read.csv('FC_single_trial_invest.csv',header=TRUE,sep=",")
dataset_BINS <- read.csv('BINS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

BOLD_mean = extract_win_or_pay_mean(dataset_BOLD,dataset_y_attack,"BOLD_","win",FALSE)
FC_mean = extract_win_or_pay_mean(dataset_FC,dataset_y_attack,"FC_","win",FALSE)
INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE)
data_all_invest = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)],BOLD_mean[,4:ncol(BOLD_mean)],FC_mean[,4:ncol(FC_mean)])
data_INS_BINS_invest = cbind(INS_mean[,c(1,4:ncol(INS_mean))],BINS_mean[,4:ncol(BINS_mean)])
data_BOLD_FC_invest = cbind(BOLD_mean[,c(1,4:ncol(BOLD_mean))],FC_mean[,4:ncol(FC_mean)])
```

## SVM-RBF
### All features
```{r svm_invest_all}
acc_all = svm_cv_accuracy_optimized(data_all_invest,5,100,"radial")
print(acc_all)
out_path = '/Users/xiaochunhan/Documents/Research/Projects/Brains_aligned_to_win/Supplement_analysis/S02_Hyperparameter_tuning'
setwd(out_path)
getwd()
file_name = 'S02_Hyper_tune_full_model.csv'
write.csv(acc_all$accuracy_details,file_name, row.names = FALSE)
```

```{r svm_invest_INS&BINS}
getwd()
file_name = 'S02_Hyper_tune_full_model.csv'
acc = read.csv(file_name)
t.test(acc$accuracy, mu = 0.5)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = svm_cv_accuracy_optimized(data_BOLD_FC_invest,5,100,"radial")
print(acc_bold_fc)
out_path = '/Users/xiaochunhan/Documents/Research/Projects/Brains_aligned_to_win/Supplement_analysis/S02_Hyperparameter_tuning'
setwd(out_path)
getwd()
file_name = 'S02_Hyper_tune_intra-brain_model.csv'
write.csv(acc_bold_fc$accuracy_details,file_name, row.names = FALSE)
```

```{r svm_invest_INS&BINS}
getwd()
file_name = 'S02_Hyper_tune_intra-brain_model.csv'
acc_ins_bins = read.csv(file_name)
t.test(acc_ins_bins$accuracy, mu = 0.5)
```

### INS and BINS
```{r svm_invest_INS&BINS}
acc_ins_bins = svm_cv_accuracy_optimized(data_INS_BINS_invest,5,100,"acc_single","radial")
print(acc_ins_bins)
out_path = '/Users/xiaochunhan/Documents/Research/Projects/Brains_aligned_to_win/Supplement_analysis/S02_Hyperparameter_tuning'
setwd(out_path)
getwd()
file_name = 'S02_Hyper_tune_inter-brain_model.csv'
write.csv(acc_ins_bins$accuracy_details,file_name, row.names = FALSE)
```

```{r svm_invest_INS&BINS}
getwd()
file_name = 'S02_Hyper_tune_inter-brain_model.csv'
acc_ins_bins = read.csv(file_name)
t.test(acc_ins_bins$accuracy, mu = 0.5)
```

## logistic_l2
### All features
```{r svm_invest_all}
acc_all = nested_cv_classifier(data_all_invest,5,100,classifier_type = "logistic_l2")
print(acc_all)
file_name = 'S02_Hyper_tune_full_model_logistic_l2.csv'
write.csv(acc_all$accuracy_details,file_name, row.names = FALSE)
```
```{r svm_invest_INS&BINS}
getwd()
file_name = 'S02_Hyper_tune_full_model_logistic_l2.csv'
acc = read.csv(file_name)
t.test(acc$accuracy, mu = 0.5)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = nested_cv_classifier(data_BOLD_FC_invest,5,100,classifier_type = "logistic_l2")
print(acc_bold_fc)
file_name = 'S02_Hyper_tune_intra-brain_model_logistic_l2.csv'
write.csv(acc_bold_fc$accuracy_details,file_name, row.names = FALSE)
t.test(acc_bold_fc$accuracy_details$accuracy, mu = 0.5)
```

### INS and BINS
```{r svm_invest_all}
acc_ins_bins = nested_cv_classifier(data_INS_BINS_invest,5,100,classifier_type = "logistic_l2")
print(acc_ins_bins)
file_name = 'S02_Hyper_tune_inter-brain_model_logistic_l2.csv'
write.csv(acc_ins_bins$accuracy_details,file_name, row.names = FALSE)
t.test(acc_ins_bins$accuracy_details$accuracy, mu = 0.5)
```

## logistic_l1
### All features
```{r svm_invest_all}
acc_all = nested_cv_classifier(data_all_invest,5,100,classifier_type = "logistic_l1",FALSE)
print(acc_all)
file_name = 'S02_Hyper_tune_full_model_logistic_l1.csv'
write.csv(acc_all$accuracy_details,file_name, row.names = FALSE)
t.test(acc_all$accuracy_details$accuracy, mu = 0.5)
```


### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = nested_cv_classifier(data_BOLD_FC_invest,5,100,classifier_type = "logistic_l1",FALSE)
print(acc_bold_fc)
file_name = 'S02_Hyper_tune_intra-brain_model_logistic_l1.csv'
write.csv(acc_bold_fc$accuracy_details,file_name, row.names = FALSE)
t.test(acc_bold_fc$accuracy_details$accuracy, mu = 0.5)
```

### INS and BINS
```{r svm_invest_all}
acc_ins_bins = nested_cv_classifier(data_INS_BINS_invest,5,100,classifier_type = "logistic_l1",FALSE)
print(acc_ins_bins)
file_name = 'S02_Hyper_tune_inter-brain_model_logistic_l1.csv'
write.csv(acc_ins_bins$accuracy_details,file_name, row.names = FALSE)
t.test(acc_ins_bins$accuracy_details$accuracy, mu = 0.5)
```

## linear_svm_l2
### All features
```{r svm_invest_all}
acc_all = nested_cv_classifier(data_all_invest,5,100,classifier_type = "linear_svm_l2")
print(acc_all)
file_name = 'S02_Hyper_tune_full_model_linear_svm_l2.csv'
write.csv(acc_all$accuracy_details,file_name, row.names = FALSE)
t.test(acc_all$accuracy_details$accuracy, mu = 0.5)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = nested_cv_classifier(data_BOLD_FC_invest,5,100,classifier_type = "linear_svm_l2")
print(acc_bold_fc)
file_name = 'S02_Hyper_tune_intra-brain_model_linear_svm_l2.csv'
write.csv(acc_bold_fc$accuracy_details,file_name, row.names = FALSE)
t.test(acc_bold_fc$accuracy_details$accuracy, mu = 0.5)
```

### INS and BINS
```{r svm_invest_all}
acc_ins_bins = nested_cv_classifier(data_INS_BINS_invest,5,100,classifier_type = "linear_svm_l2")
print(acc_ins_bins)
file_name = 'S02_Hyper_tune_inter-brain_model_linear_svm_l2.csv'
write.csv(acc_ins_bins$accuracy_details,file_name, row.names = FALSE)
t.test(acc_ins_bins$accuracy_details$accuracy, mu = 0.5)
```

## linear_svm_l1
### All features
```{r svm_invest_all}
acc_all = nested_cv_classifier(data_all_invest,5,100,classifier_type = "linear_svm_l1")
print(acc_all)
file_name = 'S02_Hyper_tune_full_model_linear_svm_l1.csv'
write.csv(acc_all$accuracy_details,file_name, row.names = FALSE)
t.test(acc_all$accuracy_details$accuracy, mu = 0.5)
```

### BOLD and FC
```{r svm_invest_BOLD&FC}
acc_bold_fc = nested_cv_classifier(data_BOLD_FC_invest,5,100,classifier_type = "linear_svm_l1")
print(acc_bold_fc)
file_name = 'S02_Hyper_tune_intra-brain_model_linear_svm_l1.csv'
write.csv(acc_bold_fc$accuracy_details,file_name, row.names = FALSE)
t.test(acc_bold_fc$accuracy_details$accuracy, mu = 0.5)
```

### INS and BINS
```{r svm_invest_all}
acc_ins_bins = nested_cv_classifier(data_INS_BINS_invest,5,100,classifier_type = "linear_svm_l1")
print(acc_ins_bins)
file_name = 'S02_Hyper_tune_inter-brain_model_linear_svm_l1.csv'
write.csv(acc_ins_bins$accuracy_details,file_name, row.names = FALSE)
t.test(acc_ins_bins$accuracy_details$accuracy, mu = 0.5)
```