---
title: "Analysis2A_SVM_prediction"
author: "Xiaochun Han"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
source("../utils/functions_library.R")
load_packages(c("dplyr", "caret", "e1071","ggplot2", "pROC", "reshape2", "rstatix"))
```

## Import data
```{r impart data}
setwd('../Data/Develop')
wd<-getwd()
dataset_BOLD <- read.csv('BOLD_single_trial_invest.csv',header=TRUE,sep=",")
dataset_FC <- read.csv('FC_single_trial_invest.csv',header=TRUE,sep=",")
dataset_BINS <- read.csv('BINS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_INS <- read.csv('INS_single_trial_invest.csv',header=TRUE,sep=",")
dataset_y <- read.csv('win_lose_and_pay_single_trial.csv',header=TRUE,sep=",")
dataset_y_attack <- dataset_y[dataset_y$role.A.1. == 1,]
dataset_y_attack <- dataset_y_attack[-c(4,14,22),] # Three sessions are deleted due to the absent of winning trial(4,22) and brain signal(14). 

BOLD_mean = extract_win_or_pay_mean(dataset_BOLD,dataset_y_attack,"BOLD_","win",FALSE)
FC_mean = extract_win_or_pay_mean(dataset_FC,dataset_y_attack,"FC_","win",FALSE)
INS_mean = extract_win_or_pay_mean(dataset_INS,dataset_y_attack,"WNS_","win",FALSE)
BINS_mean = extract_win_or_pay_mean(dataset_BINS,dataset_y_attack,"BNS_","win",FALSE)
data_all_invest = cbind(BOLD_mean[,c(1,3:ncol(BOLD_mean))],FC_mean[,3:ncol(FC_mean)],INS_mean[,3:ncol(INS_mean)],BINS_mean[,3:ncol(BINS_mean)])
data_all_invest_rev = data_all_invest[rev(rownames(data_all_invest)),]
data_all_invest_both = as.matrix(data_all_invest_rev[,2:ncol(data_all_invest_rev)])

data_INS_BINS_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)])
data_BOLD_FC_invest = cbind(BOLD_mean[,c(1,3:ncol(BOLD_mean))],FC_mean[,3:ncol(FC_mean)])

data_WNS_invest = INS_mean[,c(1,3:ncol(INS_mean))]
data_BNS_invest = BINS_mean[,c(1,3:ncol(BINS_mean))]
data_BOLD_invest = BOLD_mean[,c(1,3:ncol(BOLD_mean))]
data_FC_invest = FC_mean[,c(1,3:ncol(FC_mean))]

data_minus_WNS_invest = cbind(BINS_mean[,c(1,3:ncol(BINS_mean))],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_BNS_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BOLD_mean[,3:ncol(BOLD_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_BOLD_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],FC_mean[,3:ncol(FC_mean)])
data_minus_FC_invest = cbind(INS_mean[,c(1,3:ncol(INS_mean))],BINS_mean[,3:ncol(BINS_mean)],BOLD_mean[,3:ncol(BOLD_mean)])
```
## Heatmap
### Both win and lose
```{r heat both}
heatmap(data_all_invest_both,Colv = NA, Rowv = NA, scale = "column", col = hcl.colors(12, "YlOrRd", rev = TRUE))
```

## Predicting win vs. lose
### All features
#### 5-fold
```{r svm_invest_all-5}
acc_all = svm_cv_accuracy(data_all_invest,5,100,"radial")
print(acc_all)
```

#### 1-session-out
```{r svm_invest_all-1}
acc_all = svm_cv_accuracy(data_all_invest,30,1,"radial")
print(acc_all)
```

### BOLD and FC
#### 5-fold
```{r svm_invest_BOLD&FC-5}
acc_bold_fc = svm_cv_accuracy(data_BOLD_FC_invest,5,100,"radial")
print(acc_bold_fc)
```

#### 1-session-out
```{r svm_invest_BOLD&FC-1}
acc_bold_fc = svm_cv_accuracy(data_BOLD_FC_invest,30,1,"radial")
print(acc_bold_fc)
```

### INS and BINS
#### 5-fold
```{r svm_invest_INS&BINS-5}
acc_ins_bins = svm_cv_accuracy(data_INS_BINS_invest,5,100,"radial")
print(acc_ins_bins)
```

#### 1-session-out
```{r svm_invest_INS&BINS-1}
acc_ins_bins = svm_cv_accuracy(data_INS_BINS_invest,30,1,"radial")
print(acc_ins_bins)
```

### minus WNS
```{r svm_invest_minus_WNS}
acc_minus_wns = svm_cv_accuracy(data_minus_WNS_invest,5,100,"radial")
print(acc_minus_wns)
```

### minus BNS
```{r svm_invest_minus_BNS}
acc_minus_bns = svm_cv_accuracy(data_minus_BNS_invest,5,100,"radial")
print(acc_minus_bns)
```

### minus BOLD
```{r svm_invest_minus_BOLD}
acc_minus_bold = svm_cv_accuracy(data_minus_BOLD_invest,5,100,"radial")
print(acc_minus_bold)
```

### minus FC
```{r svm_invest_minus_FC}
acc_minus_fc = svm_cv_accuracy(data_minus_FC_invest,5,100,"radial")
print(acc_minus_fc)
```

### INS
```{r svm_invest_INS}
acc_wns = svm_cv_accuracy(data_WNS_invest,5,100,"radial")
print(acc_wns)
```

### BNS
```{r svm_invest_BNS}
acc_bns = svm_cv_accuracy(data_BNS_invest,5,100,"radial")
print(acc_bns)
```

### BOLD
```{r svm_invest_BOLD}
acc_bold = svm_cv_accuracy(data_BOLD_invest,5,100,"radial")
print(acc_bold)
```

### FC
```{r svm_invest_FC}
acc_fc = svm_cv_accuracy(data_FC_invest,5,100,"radial")
print(acc_fc)
```
